// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261001112651_Chay_lan_03")]
    partial class Chay_lan_03
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bánh kẹo & Đồ ăn vặt",
                            Description = "Snack, bánh quy, kẹo dẻo"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Nước giải khát & Trà",
                            Description = "Nước ngọt, nước khoáng, trà"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sữa & Sản phẩm từ sữa",
                            Description = "Sữa tươi, sữa chua, phô mai"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Mì gói & Thực phẩm ăn liền",
                            Description = "Mì ăn liền, phở khô, cháo gói"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Gia vị & Dầu ăn",
                            Description = "Nước mắm, hạt nêm, dầu thực vật"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "893456789001",
                            CategoryId = 1,
                            Price = 12500m,
                            ProductName = "Snack Khoai Tây O'Star Gói 60g",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "893456789002",
                            CategoryId = 1,
                            Price = 135000m,
                            ProductName = "Bánh Quy Bơ Danisa Hộp Thiếc 454g",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "893456789003",
                            CategoryId = 2,
                            Price = 10000m,
                            ProductName = "Nước Ngọt Coca Cola Lon 320ml",
                            StockQuantity = 320
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "893456789004",
                            CategoryId = 2,
                            Price = 6000m,
                            ProductName = "Nước Khoáng Lavie Chai 500ml",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "893456789005",
                            CategoryId = 3,
                            Price = 34500m,
                            ProductName = "Sữa Tươi Tiệt Trùng Vinamilk 1L",
                            StockQuantity = 85
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "893456789006",
                            CategoryId = 4,
                            Price = 4500m,
                            ProductName = "Mì Tôm Hảo Hảo Chua Cay Gói 75g",
                            StockQuantity = 500
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "893456789007",
                            CategoryId = 5,
                            Price = 125000m,
                            ProductName = "Dầu Ăn Simply Nguyên Chất Can 2L",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "893456789008",
                            CategoryId = 5,
                            Price = 30000m,
                            ProductName = "Nước Mắm Nam Ngư Chai 900ml",
                            StockQuantity = 90
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
